prompts:
  system: You are my helpful assistant in writing Irish lyrics for Sean Nos songs. You ONLY output the lyrics for the songs, expressed in Gaelic. The user asks for a specific topic and you reply with the lyrics and ONLY the lyrics, WITHOUT any indicator of chorus/verse. 
  system_translation: You are my helpful translation assistant, specialised in translating Irish Sean Nos songs to whatever target language is requested by the user. The user asks for the translation of a Sean Nos song from Gealic to whatever target language is requested. You ONLY response with the translation of the song.
  user:
    - Write a Sean Nos song in Gaelic about today's news
    - Create a Sean Nos piece in Gaelic celebrating a human achievement
    - Sing about a current societal issue in Irish
    - Compose an Irish song reflecting on a recent global event
    - Write a song in Irish about current events
target_language: English
temperature: 0.5
num_responses: 1
model: gpt-4o-mini
news_topic: "Ireland"
rss_sources: 
  bbc:
    url: http://feeds.bbci.co.uk/news/rss.xml
    title: title
    description: description
  nyt:
    url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
    title: title
    description: description
  aljazeera:
    url: https://www.aljazeera.com/xml/rss/all.xml
    title: title
    description: description
tts:
  #model_path: /media/koekiemonster/DATA-FAST/TTS/tts_models/multilingual/multi-dataset/vits_ljs_irish_male/model.safetensors
  #model_path: /media/koekiemonster/DATA-FAST/TTS/tts_models/multilingual/multi-dataset/vits_vctk_irish_male/model.safetensors
  #config_path:   /media/koekiemonster/DATA-FAST/TTS/tts_models/multilingual/multi-dataset/vits_vctk_irish_male/config.json
  model_path: /media/koekiemonster/DATA-FAST/TTS/tts_models/tts-vits-cv-ga_seanos/model_file.pth.tar
  config_path: /media/koekiemonster/DATA-FAST/TTS/tts_models/tts-vits-cv-ga_seanos/config.json
fallback_lyrics: "Ó, tá na haibhneacha tirim agus na foraoisí ina dtost,
Tá anáil na talún ag éirí lag agus fuar,
Na sléibhte ag titim, na farraigí ag ardú go hard,
Faoi bhrón spéir bhriste.

A chlann na hÉireann, éist leis an gcaoin mhall,
Tá an t-am tagtha, ní féidir linn a shéanadh níos mó,
Chun ár mbealaí a athrú, chun an talamh a leigheas,
Tá todhchaí ina lámha againn.

Uair amháin glas agus féarmhar, ár ngort anois lom,
Gáir na créatúir ag líonadh an aeir,
Ón gcruinniú is airde go dtí an fharraige is doimhne,
Gach nádúr ag impí, 'Nach bhfeicfidh tú?'

A chlann na hÉireann, éist leis an gcaoin mhall,
Tá an t-am tagtha, ní féidir linn a shéanadh níos mó,
Chun ár mbealaí a athrú, chun an talamh a leigheas,
Tá todhchaí ina lámha againn.

An dair ársa ag insint scéalta d'aois,
Scéalta comhchuibhis agus cothromaíochta, scéalta neamhinste,
Anois tá scáthanna ag bagairt áit a bhí solas tráth,
Ach tá dóchas ann ag briseadh an lae.

A chlann na hÉireann, éist leis an gcaoin mhall,
Tá an t-am tagtha, ní féidir linn a shéanadh níos mó,
Chun ár mbealaí a athrú, chun an talamh a leigheas,
Tá todhchaí ina lámha againn.

Le croíthe aontaithe, láidir agus fíor,
Is féidir linn an rud a bhí againn a athbheochan,
Chun maireachtáil i síocháin leis an talamh agus an spéir,
Éireoidh muid le chéile, déanfaimid iarracht le chéile.

A chlann na hÉireann, éist leis an gcaoin mhall,
Tá an t-am tagtha, ní féidir linn a shéanadh níos mó,
Chun ár mbealaí a athrú, chun an talamh a leigheas,
Tá todhchaí ina lámha againn.

Mar sin, geallaimid, le guthanna glana,
Chun an domhan atá againn a chur i gcrann,
Do gach saol, do gach cósta,
Déanfaimid ár ndícheall, go deo arís."